#ifndef DCOOL_CORE_SELECT_HPP_INCLUDED_
#	define DCOOL_CORE_SELECT_HPP_INCLUDED_ 1

#	define DCOOL_CORE_SELECT_0_(value_, ...) value_
#	define DCOOL_CORE_SELECT_1_(placeholder1_, value_, ...) value_
#	define DCOOL_CORE_SELECT_2_(placeholder1_, placeholder2_, value_, ...) value_
#	define DCOOL_CORE_SELECT_3_(placeholder1_, placeholder2_, placeholder3_, value_, ...) value_
#	define DCOOL_CORE_SELECT_4_(placeholder1_, placeholder2_, placeholder3_, placeholder4_, value_, ...) value_
#	define DCOOL_CORE_SELECT_5_(placeholder1_, placeholder2_, placeholder3_, placeholder4_, placeholder5_, value_, ...) value_

#	define DCOOL_CORE_SELECT_6_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_7_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_8_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_9_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_10_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_11_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_12_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_13_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_14_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_15_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_16_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_17_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_18_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_19_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_20_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_21_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_22_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_23_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_24_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_25_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_26_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_27_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_28_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_29_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_30_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_31_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_32_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_33_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_34_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_35_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		placeholder35_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_36_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		placeholder35_, \
		placeholder36_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_37_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		placeholder35_, \
		placeholder36_, \
		placeholder37_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_38_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		placeholder35_, \
		placeholder36_, \
		placeholder37_, \
		placeholder38_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_39_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		placeholder35_, \
		placeholder36_, \
		placeholder37_, \
		placeholder38_, \
		placeholder39_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_40_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		placeholder35_, \
		placeholder36_, \
		placeholder37_, \
		placeholder38_, \
		placeholder39_, \
		placeholder40_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_41_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		placeholder35_, \
		placeholder36_, \
		placeholder37_, \
		placeholder38_, \
		placeholder39_, \
		placeholder40_, \
		placeholder41_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_42_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		placeholder35_, \
		placeholder36_, \
		placeholder37_, \
		placeholder38_, \
		placeholder39_, \
		placeholder40_, \
		placeholder41_, \
		placeholder42_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_43_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		placeholder35_, \
		placeholder36_, \
		placeholder37_, \
		placeholder38_, \
		placeholder39_, \
		placeholder40_, \
		placeholder41_, \
		placeholder42_, \
		placeholder43_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_44_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		placeholder35_, \
		placeholder36_, \
		placeholder37_, \
		placeholder38_, \
		placeholder39_, \
		placeholder40_, \
		placeholder41_, \
		placeholder42_, \
		placeholder43_, \
		placeholder44_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_45_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		placeholder35_, \
		placeholder36_, \
		placeholder37_, \
		placeholder38_, \
		placeholder39_, \
		placeholder40_, \
		placeholder41_, \
		placeholder42_, \
		placeholder43_, \
		placeholder44_, \
		placeholder45_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_46_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		placeholder35_, \
		placeholder36_, \
		placeholder37_, \
		placeholder38_, \
		placeholder39_, \
		placeholder40_, \
		placeholder41_, \
		placeholder42_, \
		placeholder43_, \
		placeholder44_, \
		placeholder45_, \
		placeholder46_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_47_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		placeholder35_, \
		placeholder36_, \
		placeholder37_, \
		placeholder38_, \
		placeholder39_, \
		placeholder40_, \
		placeholder41_, \
		placeholder42_, \
		placeholder43_, \
		placeholder44_, \
		placeholder45_, \
		placeholder46_, \
		placeholder47_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_48_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		placeholder35_, \
		placeholder36_, \
		placeholder37_, \
		placeholder38_, \
		placeholder39_, \
		placeholder40_, \
		placeholder41_, \
		placeholder42_, \
		placeholder43_, \
		placeholder44_, \
		placeholder45_, \
		placeholder46_, \
		placeholder47_, \
		placeholder48_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_49_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		placeholder35_, \
		placeholder36_, \
		placeholder37_, \
		placeholder38_, \
		placeholder39_, \
		placeholder40_, \
		placeholder41_, \
		placeholder42_, \
		placeholder43_, \
		placeholder44_, \
		placeholder45_, \
		placeholder46_, \
		placeholder47_, \
		placeholder48_, \
		placeholder49_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_50_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		placeholder35_, \
		placeholder36_, \
		placeholder37_, \
		placeholder38_, \
		placeholder39_, \
		placeholder40_, \
		placeholder41_, \
		placeholder42_, \
		placeholder43_, \
		placeholder44_, \
		placeholder45_, \
		placeholder46_, \
		placeholder47_, \
		placeholder48_, \
		placeholder49_, \
		placeholder50_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_51_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		placeholder35_, \
		placeholder36_, \
		placeholder37_, \
		placeholder38_, \
		placeholder39_, \
		placeholder40_, \
		placeholder41_, \
		placeholder42_, \
		placeholder43_, \
		placeholder44_, \
		placeholder45_, \
		placeholder46_, \
		placeholder47_, \
		placeholder48_, \
		placeholder49_, \
		placeholder50_, \
		placeholder51_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_52_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		placeholder35_, \
		placeholder36_, \
		placeholder37_, \
		placeholder38_, \
		placeholder39_, \
		placeholder40_, \
		placeholder41_, \
		placeholder42_, \
		placeholder43_, \
		placeholder44_, \
		placeholder45_, \
		placeholder46_, \
		placeholder47_, \
		placeholder48_, \
		placeholder49_, \
		placeholder50_, \
		placeholder51_, \
		placeholder52_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_53_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		placeholder35_, \
		placeholder36_, \
		placeholder37_, \
		placeholder38_, \
		placeholder39_, \
		placeholder40_, \
		placeholder41_, \
		placeholder42_, \
		placeholder43_, \
		placeholder44_, \
		placeholder45_, \
		placeholder46_, \
		placeholder47_, \
		placeholder48_, \
		placeholder49_, \
		placeholder50_, \
		placeholder51_, \
		placeholder52_, \
		placeholder53_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_54_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		placeholder35_, \
		placeholder36_, \
		placeholder37_, \
		placeholder38_, \
		placeholder39_, \
		placeholder40_, \
		placeholder41_, \
		placeholder42_, \
		placeholder43_, \
		placeholder44_, \
		placeholder45_, \
		placeholder46_, \
		placeholder47_, \
		placeholder48_, \
		placeholder49_, \
		placeholder50_, \
		placeholder51_, \
		placeholder52_, \
		placeholder53_, \
		placeholder54_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_55_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		placeholder35_, \
		placeholder36_, \
		placeholder37_, \
		placeholder38_, \
		placeholder39_, \
		placeholder40_, \
		placeholder41_, \
		placeholder42_, \
		placeholder43_, \
		placeholder44_, \
		placeholder45_, \
		placeholder46_, \
		placeholder47_, \
		placeholder48_, \
		placeholder49_, \
		placeholder50_, \
		placeholder51_, \
		placeholder52_, \
		placeholder53_, \
		placeholder54_, \
		placeholder55_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_56_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		placeholder35_, \
		placeholder36_, \
		placeholder37_, \
		placeholder38_, \
		placeholder39_, \
		placeholder40_, \
		placeholder41_, \
		placeholder42_, \
		placeholder43_, \
		placeholder44_, \
		placeholder45_, \
		placeholder46_, \
		placeholder47_, \
		placeholder48_, \
		placeholder49_, \
		placeholder50_, \
		placeholder51_, \
		placeholder52_, \
		placeholder53_, \
		placeholder54_, \
		placeholder55_, \
		placeholder56_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_57_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		placeholder35_, \
		placeholder36_, \
		placeholder37_, \
		placeholder38_, \
		placeholder39_, \
		placeholder40_, \
		placeholder41_, \
		placeholder42_, \
		placeholder43_, \
		placeholder44_, \
		placeholder45_, \
		placeholder46_, \
		placeholder47_, \
		placeholder48_, \
		placeholder49_, \
		placeholder50_, \
		placeholder51_, \
		placeholder52_, \
		placeholder53_, \
		placeholder54_, \
		placeholder55_, \
		placeholder56_, \
		placeholder57_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_58_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		placeholder35_, \
		placeholder36_, \
		placeholder37_, \
		placeholder38_, \
		placeholder39_, \
		placeholder40_, \
		placeholder41_, \
		placeholder42_, \
		placeholder43_, \
		placeholder44_, \
		placeholder45_, \
		placeholder46_, \
		placeholder47_, \
		placeholder48_, \
		placeholder49_, \
		placeholder50_, \
		placeholder51_, \
		placeholder52_, \
		placeholder53_, \
		placeholder54_, \
		placeholder55_, \
		placeholder56_, \
		placeholder57_, \
		placeholder58_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_59_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		placeholder35_, \
		placeholder36_, \
		placeholder37_, \
		placeholder38_, \
		placeholder39_, \
		placeholder40_, \
		placeholder41_, \
		placeholder42_, \
		placeholder43_, \
		placeholder44_, \
		placeholder45_, \
		placeholder46_, \
		placeholder47_, \
		placeholder48_, \
		placeholder49_, \
		placeholder50_, \
		placeholder51_, \
		placeholder52_, \
		placeholder53_, \
		placeholder54_, \
		placeholder55_, \
		placeholder56_, \
		placeholder57_, \
		placeholder58_, \
		placeholder59_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_60_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		placeholder35_, \
		placeholder36_, \
		placeholder37_, \
		placeholder38_, \
		placeholder39_, \
		placeholder40_, \
		placeholder41_, \
		placeholder42_, \
		placeholder43_, \
		placeholder44_, \
		placeholder45_, \
		placeholder46_, \
		placeholder47_, \
		placeholder48_, \
		placeholder49_, \
		placeholder50_, \
		placeholder51_, \
		placeholder52_, \
		placeholder53_, \
		placeholder54_, \
		placeholder55_, \
		placeholder56_, \
		placeholder57_, \
		placeholder58_, \
		placeholder59_, \
		placeholder60_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_61_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		placeholder35_, \
		placeholder36_, \
		placeholder37_, \
		placeholder38_, \
		placeholder39_, \
		placeholder40_, \
		placeholder41_, \
		placeholder42_, \
		placeholder43_, \
		placeholder44_, \
		placeholder45_, \
		placeholder46_, \
		placeholder47_, \
		placeholder48_, \
		placeholder49_, \
		placeholder50_, \
		placeholder51_, \
		placeholder52_, \
		placeholder53_, \
		placeholder54_, \
		placeholder55_, \
		placeholder56_, \
		placeholder57_, \
		placeholder58_, \
		placeholder59_, \
		placeholder60_, \
		placeholder61_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_62_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		placeholder35_, \
		placeholder36_, \
		placeholder37_, \
		placeholder38_, \
		placeholder39_, \
		placeholder40_, \
		placeholder41_, \
		placeholder42_, \
		placeholder43_, \
		placeholder44_, \
		placeholder45_, \
		placeholder46_, \
		placeholder47_, \
		placeholder48_, \
		placeholder49_, \
		placeholder50_, \
		placeholder51_, \
		placeholder52_, \
		placeholder53_, \
		placeholder54_, \
		placeholder55_, \
		placeholder56_, \
		placeholder57_, \
		placeholder58_, \
		placeholder59_, \
		placeholder60_, \
		placeholder61_, \
		placeholder62_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_63_( \
		placeholder1_, \
		placeholder2_, \
		placeholder3_, \
		placeholder4_, \
		placeholder5_, \
		placeholder6_, \
		placeholder7_, \
		placeholder8_, \
		placeholder9_, \
		placeholder10_, \
		placeholder11_, \
		placeholder12_, \
		placeholder13_, \
		placeholder14_, \
		placeholder15_, \
		placeholder16_, \
		placeholder17_, \
		placeholder18_, \
		placeholder19_, \
		placeholder20_, \
		placeholder21_, \
		placeholder22_, \
		placeholder23_, \
		placeholder24_, \
		placeholder25_, \
		placeholder26_, \
		placeholder27_, \
		placeholder28_, \
		placeholder29_, \
		placeholder30_, \
		placeholder31_, \
		placeholder32_, \
		placeholder33_, \
		placeholder34_, \
		placeholder35_, \
		placeholder36_, \
		placeholder37_, \
		placeholder38_, \
		placeholder39_, \
		placeholder40_, \
		placeholder41_, \
		placeholder42_, \
		placeholder43_, \
		placeholder44_, \
		placeholder45_, \
		placeholder46_, \
		placeholder47_, \
		placeholder48_, \
		placeholder49_, \
		placeholder50_, \
		placeholder51_, \
		placeholder52_, \
		placeholder53_, \
		placeholder54_, \
		placeholder55_, \
		placeholder56_, \
		placeholder57_, \
		placeholder58_, \
		placeholder59_, \
		placeholder60_, \
		placeholder61_, \
		placeholder62_, \
		placeholder63_, \
		value_, \
		... \
	) value_

#	define DCOOL_CORE_SELECT_0(...) DCOOL_CORE_SELECT_0_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_1(...) DCOOL_CORE_SELECT_1_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_2(...) DCOOL_CORE_SELECT_2_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_3(...) DCOOL_CORE_SELECT_3_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_4(...) DCOOL_CORE_SELECT_4_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_5(...) DCOOL_CORE_SELECT_5_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_6(...) DCOOL_CORE_SELECT_6_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_7(...) DCOOL_CORE_SELECT_7_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_8(...) DCOOL_CORE_SELECT_8_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_9(...) DCOOL_CORE_SELECT_9_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_10(...) DCOOL_CORE_SELECT_10_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_11(...) DCOOL_CORE_SELECT_11_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_12(...) DCOOL_CORE_SELECT_12_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_13(...) DCOOL_CORE_SELECT_13_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_14(...) DCOOL_CORE_SELECT_14_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_15(...) DCOOL_CORE_SELECT_15_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_16(...) DCOOL_CORE_SELECT_16_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_17(...) DCOOL_CORE_SELECT_17_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_18(...) DCOOL_CORE_SELECT_18_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_19(...) DCOOL_CORE_SELECT_19_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_20(...) DCOOL_CORE_SELECT_20_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_21(...) DCOOL_CORE_SELECT_21_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_22(...) DCOOL_CORE_SELECT_22_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_23(...) DCOOL_CORE_SELECT_23_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_24(...) DCOOL_CORE_SELECT_24_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_25(...) DCOOL_CORE_SELECT_25_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_26(...) DCOOL_CORE_SELECT_26_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_27(...) DCOOL_CORE_SELECT_27_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_28(...) DCOOL_CORE_SELECT_28_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_29(...) DCOOL_CORE_SELECT_29_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_30(...) DCOOL_CORE_SELECT_30_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_31(...) DCOOL_CORE_SELECT_31_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_32(...) DCOOL_CORE_SELECT_32_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_33(...) DCOOL_CORE_SELECT_33_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_34(...) DCOOL_CORE_SELECT_34_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_35(...) DCOOL_CORE_SELECT_35_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_36(...) DCOOL_CORE_SELECT_36_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_37(...) DCOOL_CORE_SELECT_37_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_38(...) DCOOL_CORE_SELECT_38_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_39(...) DCOOL_CORE_SELECT_39_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_40(...) DCOOL_CORE_SELECT_40_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_41(...) DCOOL_CORE_SELECT_41_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_42(...) DCOOL_CORE_SELECT_42_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_43(...) DCOOL_CORE_SELECT_43_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_44(...) DCOOL_CORE_SELECT_44_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_45(...) DCOOL_CORE_SELECT_45_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_46(...) DCOOL_CORE_SELECT_46_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_47(...) DCOOL_CORE_SELECT_47_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_48(...) DCOOL_CORE_SELECT_48_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_49(...) DCOOL_CORE_SELECT_49_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_50(...) DCOOL_CORE_SELECT_50_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_51(...) DCOOL_CORE_SELECT_51_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_52(...) DCOOL_CORE_SELECT_52_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_53(...) DCOOL_CORE_SELECT_53_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_54(...) DCOOL_CORE_SELECT_54_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_55(...) DCOOL_CORE_SELECT_55_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_56(...) DCOOL_CORE_SELECT_56_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_57(...) DCOOL_CORE_SELECT_57_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_58(...) DCOOL_CORE_SELECT_58_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_59(...) DCOOL_CORE_SELECT_59_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_60(...) DCOOL_CORE_SELECT_60_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_61(...) DCOOL_CORE_SELECT_61_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_62(...) DCOOL_CORE_SELECT_62_(__VA_ARGS__)
#	define DCOOL_CORE_SELECT_63(...) DCOOL_CORE_SELECT_63_(__VA_ARGS__)

#endif
