#ifndef DCOOL_CONSOLE_BASIC_HPP_INCLUDED_
#	define DCOOL_CONSOLE_BASIC_HPP_INCLUDED_ 1

#	include <string>

#	define DCOOL_CONSOLE_ESCAPE "\x1B"
#	define DCOOL_CONSOLE_CSI DCOOL_CONSOLE_ESCAPE "["

#endif
