#ifndef DCOOL_CONFIG_H_INCLUDED_
#	define DCOOL_CONFIG_H_INCLUDED_ 1

#	include <dcool/basic.h>
#	include <dcool/version.h>

#	define DCOOL_MACRO_DESCRIPTION(macroName_) #macroName_ " = " DCOOL_TO_STR_(macroName_)

#	ifdef DCOOLER_ENABLE_DEBUG
#		if DCOOLER_ENABLE_DEBUG
#			define DCOOL_DEBUG_ENABLED 1
#		else
#			define DCOOL_DEBUG_ENABLED 0
#		endif
#	else
# 	if defined(NDEBUG)
#			define DCOOL_DEBUG_ENABLED 0
#		else
#			define DCOOL_DEBUG_ENABLED 1
#		endif
#	endif

#	ifdef DCOOLER_ENABLE_AGGRESSIVE_DEBUG
#		if DCOOLER_ENABLE_AGGRESSIVE_DEBUG
#			define DCOOL_AGGRESSIVE_DEBUG_ENABLED DCOOL_DEBUG_ENABLED
#		else
#			define DCOOL_AGGRESSIVE_DEBUG_ENABLED 0
#		endif
#	else
#		define DCOOL_AGGRESSIVE_DEBUG_ENABLED 0
#	endif

#	ifdef DCOOLER_ENABLE_POINTER_FOLDING_BY_ALIGNMENT
#		if DCOOLER_ENABLE_POINTER_FOLDING_BY_ALIGNMENT
#			define DCOOL_POINTER_FOLDING_BY_ALIGNMENT_ENABLED 1
#		else
#			define DCOOL_POINTER_FOLDING_BY_ALIGNMENT_ENABLED 0
#		endif
#	else
#		define DCOOL_POINTER_FOLDING_BY_ALIGNMENT_ENABLED 0
#	endif

#	define DCOOL_COMMON_CONFIG_NATIVE_DESCRIPTION_HELPER(seperator_, ending_) \
	DCOOL_MACRO_DESCRIPTION(DCOOL_DEBUG_ENABLED) seperator_ \
	DCOOL_MACRO_DESCRIPTION(DCOOL_AGGRESSIVE_DEBUG_ENABLED) seperator_ \
	DCOOL_MACRO_DESCRIPTION(DCOOL_POINTER_FOLDING_BY_ALIGNMENT_ENABLED) ending_

#	define DCOOL_COMMON_CONFIG_DESCRIPTION_HELPER(seperator_, ending_) \
	DCOOL_STR_TO_U8_(DCOOL_COMMON_CONFIG_NATIVE_DESCRIPTION_HELPER(seperator_, ending_))

#	define DCOOL_COMMON_CONFIG_NATIVE_DESCRIPTION DCOOL_COMMON_CONFIG_NATIVE_DESCRIPTION_HELPER("\n", "\n")
#	define DCOOL_COMMON_CONFIG_DESCRIPTION DCOOL_STR_TO_U8_(DCOOL_COMMON_CONFIG_NATIVE_DESCRIPTION)

#	define DCOOL_COMMON_SELF_NATIVE_DESCRIPTION \
	"dcool " DCOOL_VERSION_NATIVE_NAME "\n\t" DCOOL_COMMON_CONFIG_NATIVE_DESCRIPTION_HELPER("\n\t", "\n")
#	define DCOOL_COMMON_SELF_DESCRIPTION DCOOL_STR_TO_U8_(DCOOL_COMMON_SELF_NATIVE_DESCRIPTION)

#endif
