#ifndef DCOOL_VERSRION_HPP_INCLUDED_
#	define DCOOL_VERSRION_HPP_INCLUDED_ 1

#	define DCOOL_MAJOR_VERSION 0
#	define DCOOL_MINOR_VERSION 7
#	define DCOOL_PATCH_VERSION 0
#	define DCOOL_VERSION_NAME u8"0.7.0"
#	define DCOOL_VERSION_NATIVE_NAME "0.7.0"

#endif
